apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    release: dyn-metrics
    app: dyn-metrics
  name: dyn-metrics
  namespace: cattle-monitoring-system
spec:
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dyn-metrics
  type: ClusterIP
