global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'dummy'
    static_configs:
      - targets: ['localhost:9999']

remote_read:
  - url: "http://127.0.0.1:10080/api/v1/read"

