{
 "title": "Eficiencia",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespaces", "label": "Namespaces", "query": { "query": "kube_namespace_labels" } },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "kube_pod_labels{namespace=~\"$namespaces\"}"
    }
   },
   {
    "name": "resolution",
    "label": "Resolucio",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "namespace: $namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespaces" },
  { "title": "CPU", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1 } },
  { "title": "Memory", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=~\"$namespaces\"}[$resolution])[$resolution:]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespaces\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespaces\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "% Limit (peak)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=~\"$namespaces\"}[$resolution])[$resolution:]))) / (sum(kube_pod_container_resource_limits{namespace=~\"$namespaces\", resource=\"cpu\"}))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "% Requests (peak)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=~\"$namespaces\"}[$resolution])[$resolution:]))) / (sum(kube_pod_container_resource_requests{namespace=~\"$namespaces\", resource=\"cpu\"}))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespaces\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespaces\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespaces\", resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "% Limit (peak)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=~\"$namespaces\"})) / (sum(kube_pod_container_resource_limits{namespace=~\"$namespaces\", resource=\"memory\"}))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "% Requested (peak)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=~\"$namespaces\"})) / (sum(kube_pod_container_resource_requests{namespace=~\"$namespaces\", resource=\"memory\"}))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "$pods",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "repeat": "pods",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=~\"$namespaces\",pod=\"$pods\"})) / (sum(kube_pod_container_resource_requests{namespace=~\"$namespaces\", resource=\"memory\",pod=\"$pods\"}))",
     "legendFormat": "MEM Req"
    },
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=~\"$namespaces\",pod=\"$pods\"})) / (sum(kube_pod_container_resource_limits{namespace=~\"$namespaces\", resource=\"memory\",pod=\"$pods\"}))",
     "legendFormat": "MEM Lim"
    },
    {
     "expr": "(sum(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=~\"$namespaces\",pod=\"$pods\"}[$resolution])[$resolution:]))) / (sum(kube_pod_container_resource_requests{namespace=~\"$namespaces\", resource=\"cpu\",pod=\"$pods\"}))",
     "legendFormat": "CPU Req"
    },
    {
     "expr": "(sum(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=~\"$namespaces\",pod=\"$pods\"}[$resolution])[$resolution:]))) / (sum(kube_pod_container_resource_limits{namespace=~\"$namespaces\", resource=\"cpu\",pod=\"$pods\"}))",
     "legendFormat": "CPU Lim"
    }
   ]
  }
 ]
}