apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-namespace-label-to-pods
spec:
  background: true
  rules:
  - name: copy-namespace-label-to-pods
    context:
    - name: namespaceLabels
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: "metadata.labels"
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
        - ingress-nginx
        - kube-node-lease
        - kube-public
        - kube-system
        - kyverno
        - local
        - local-path-storage
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            projectid: "{{ namespaceLabels.\"field.cattle.io/projectId\" || 'unknown' }}"
