apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: recording-rules
  name: project-metrics-k8s-rules
  namespace: cattle-monitoring-system
spec:
  groups:
  - name: project_cpu_usage
    interval: 1m
    rules:
    - record: project:container_cpu_usage_seconds_total:rate1m
      expr: |
        sum(
          rate(container_cpu_usage_seconds_total[1m]) * on (namespace, pod) group_left(label_projectid, cluster_id)
          kube_pod_labels{label_projectid!=""}
        ) by (pod, namespace, label_projectid, cluster_id)
  - name: project_pod_resource_requests
    interval: 1m
    rules:
    - record: project:kube_pod_container_resource_requests
      expr: |
        sum(
          kube_pod_container_resource_requests * on (namespace, pod) group_left(label_projectid, cluster_id)
          kube_pod_labels{label_projectid!=""}
        ) by (pod, namespace, label_projectid, cluster_id, resource)
  - name: project_pod_resource_limits
    interval: 1m
    rules:
    - record: project:kube_pod_container_resource_limits
      expr: |
        sum(
          kube_pod_container_resource_limits * on (namespace, pod) group_left(label_projectid, cluster_id)
          kube_pod_labels{label_projectid!=""}
        ) by (pod, namespace, label_projectid, cluster_id, resource)

