apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dyn-kube-state-metrics-global
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list","get","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dyn-kube-state-metrics-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dyn-kube-state-metrics-global
subjects:
- kind: ServiceAccount
  name: dyn-p-85ldn-kube-state-metrics
  namespace: cattle-monitoring-system
- kind: ServiceAccount
  name: dyn-p-crxgd-kube-state-metrics
  namespace: cattle-monitoring-system
- kind: ServiceAccount
  name: dyn-p-crxgd-kube-state-metrics
  namespace: cattle-monitoring-system
- kind: ServiceAccount
  name: dyn-p-gnpg5-kube-state-metrics
  namespace: cattle-monitoring-system
- kind: ServiceAccount
  name: dyn-p-phvpm-kube-state-metrics
  namespace: cattle-monitoring-system

